# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - J1_pris_
      - J1_rotate_
      - J2_
      - J3_
      - J4_x_
      - J4_y_
    action_ns: follow_joint_trajectory
    default: true