# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - J1_pris
      - J1_rotate
      - J2
      - J3
      - J4_x
      - J4_y
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity