# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - body_controller

  body_controller:
    type: FollowJointTrajectory
    joints:
      - r1
      - j2
      - j3
      - j4
      - j7
      - j5
      - j6