engineering_robot_controller:
    # Controller manager configuration
    minOrientationTolerance: 0.5
    minPositionTolerance: 0.01
    maxOrientationTolerance: 0.6
    maxPositionTolerance: 0.018
    AllowPlanAttempt: 4
    minPlanTime: 5
    maxPlanTime: 5
    ARM_CONTROL_GROUP: "arm"
    END_EFFECTOR_CONTROL_GROUP : "sucker"